"""
AceCPAs Backend - Open Items Router
API endpoints for open item (audit question) management.
"""
from typing import Optional
from datetime import datetime

from fastapi import APIRouter, HTTPException, Query

from app.config import get_settings
from app.database import get_supabase_admin_client
from app.models.schemas import (
    OpenItemResponse,
    OpenItemCreate,
    OpenItemUpdateRequest,
    OpenItemStatus,
    ErrorResponse
)

router = APIRouter()
settings = get_settings()


@router.get(
    "/deals/{deal_id}/open-items",
    response_model=list[OpenItemResponse],
    summary="List open items for a deal",
    description="Get all audit questions/open items for a specific deal."
)
async def list_open_items(
    deal_id: str,
    status: Optional[str] = Query(None, description="Filter by status (draft, sent, responded, resolved)"),
    include_resolved: bool = Query(False, description="Include resolved items")
):
    """
    List all open items for a deal.
    
    Open items are audit questions generated by the auditor agent
    that need client clarification.
    """
    client = get_supabase_admin_client()
    
    query = client.table("open_items").select(
        "*, gl_transactions(id, raw_date, raw_account, raw_desc, vendor, amount, confidence)"
    ).eq("deal_id", deal_id)
    
    if status:
        query = query.eq("status", status)
    elif not include_resolved:
        query = query.neq("status", "resolved")
    
    result = query.order("created_at", desc=True).execute()
    
    # Transform response
    items = []
    for row in result.data:
        transaction = row.pop('gl_transactions', None)
        row['transaction'] = transaction
        items.append(row)
    
    return items


@router.get(
    "/open-items/{item_id}",
    response_model=OpenItemResponse,
    responses={404: {"model": ErrorResponse}},
    summary="Get open item by ID"
)
async def get_open_item(item_id: str):
    """Get a specific open item by ID."""
    client = get_supabase_admin_client()
    
    result = client.table("open_items").select(
        "*, gl_transactions(*)"
    ).eq("id", item_id).single().execute()
    
    if not result.data:
        raise HTTPException(status_code=404, detail="Open item not found")
    
    transaction = result.data.pop('gl_transactions', None)
    result.data['transaction'] = transaction
    
    return result.data


@router.post(
    "/deals/{deal_id}/open-items",
    response_model=OpenItemResponse,
    status_code=201,
    summary="Create an open item"
)
async def create_open_item(
    deal_id: str,
    item: OpenItemCreate
):
    """Manually create an open item (audit question)."""
    client = get_supabase_admin_client()
    
    item_data = item.model_dump()
    item_data['deal_id'] = deal_id
    
    result = client.table("open_items").insert(item_data).execute()
    return result.data[0]


@router.patch(
    "/open-items/{item_id}",
    response_model=OpenItemResponse,
    responses={404: {"model": ErrorResponse}},
    summary="Update an open item"
)
async def update_open_item(
    item_id: str,
    update: OpenItemUpdateRequest
):
    """
    Update an open item's status or add client response.
    
    Status flow: draft → sent → responded → resolved
    """
    client = get_supabase_admin_client()
    
    update_data = {}
    
    if update.status is not None:
        update_data['status'] = update.status.value
        
        # Set timestamps based on status
        if update.status == OpenItemStatus.SENT:
            update_data['sent_at'] = datetime.utcnow().isoformat()
        elif update.status == OpenItemStatus.RESOLVED:
            update_data['resolved_at'] = datetime.utcnow().isoformat()
    
    if update.client_response is not None:
        update_data['client_response'] = update.client_response
        # Auto-update status to responded if response provided
        if 'status' not in update_data:
            update_data['status'] = OpenItemStatus.RESPONDED.value
    
    if not update_data:
        raise HTTPException(status_code=400, detail="No update data provided")
    
    result = client.table("open_items").update(
        update_data
    ).eq("id", item_id).execute()
    
    if not result.data:
        raise HTTPException(status_code=404, detail="Open item not found")
    
    return result.data[0]


@router.delete(
    "/open-items/{item_id}",
    status_code=204,
    responses={404: {"model": ErrorResponse}},
    summary="Delete an open item"
)
async def delete_open_item(item_id: str):
    """Delete an open item."""
    client = get_supabase_admin_client()
    
    result = client.table("open_items").delete().eq("id", item_id).execute()
    
    if not result.data:
        raise HTTPException(status_code=404, detail="Open item not found")
    
    return None


@router.post(
    "/open-items/{item_id}/send",
    response_model=OpenItemResponse,
    summary="Mark open item as sent"
)
async def send_open_item(item_id: str):
    """
    Mark an open item as sent to the client.
    
    In a production system, this would integrate with email sending.
    """
    client = get_supabase_admin_client()
    
    result = client.table("open_items").update({
        "status": "sent",
        "sent_at": datetime.utcnow().isoformat()
    }).eq("id", item_id).execute()
    
    if not result.data:
        raise HTTPException(status_code=404, detail="Open item not found")
    
    return result.data[0]


@router.post(
    "/open-items/{item_id}/resolve",
    response_model=OpenItemResponse,
    summary="Resolve an open item"
)
async def resolve_open_item(
    item_id: str,
    resolution_note: Optional[str] = Query(None, description="Optional resolution note")
):
    """Mark an open item as resolved."""
    client = get_supabase_admin_client()
    
    update_data = {
        "status": "resolved",
        "resolved_at": datetime.utcnow().isoformat()
    }
    
    if resolution_note:
        # Append resolution note to client_response
        current = client.table("open_items").select("client_response").eq("id", item_id).single().execute()
        if current.data:
            existing = current.data.get('client_response') or ''
            update_data['client_response'] = f"{existing}\n\n[Resolution]: {resolution_note}".strip()
    
    result = client.table("open_items").update(update_data).eq("id", item_id).execute()
    
    if not result.data:
        raise HTTPException(status_code=404, detail="Open item not found")
    
    return result.data[0]


@router.get(
    "/deals/{deal_id}/open-items/summary",
    summary="Get open items summary"
)
async def get_open_items_summary(deal_id: str):
    """Get summary statistics for open items."""
    client = get_supabase_admin_client()
    
    # Get counts by status
    all_items = client.table("open_items").select(
        "status", count="exact"
    ).eq("deal_id", deal_id).execute()
    
    # Count by status
    status_counts = {
        'draft': 0,
        'sent': 0,
        'responded': 0,
        'resolved': 0
    }
    
    for item in all_items.data:
        status = item.get('status', 'draft')
        status_counts[status] = status_counts.get(status, 0) + 1
    
    # Get counts by flag reason
    reason_result = client.table("open_items").select("flag_reason").eq("deal_id", deal_id).execute()
    
    reason_counts = {}
    for item in reason_result.data:
        reason = item.get('flag_reason') or 'unknown'
        reason_counts[reason] = reason_counts.get(reason, 0) + 1
    
    return {
        "total": all_items.count or 0,
        "by_status": status_counts,
        "by_reason": reason_counts,
        "pending": status_counts['draft'] + status_counts['sent'],
        "needs_review": status_counts['responded']
    }
